// nmpv3-plus/examples/svelte/NMPv3PlusPlayer.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { createNMPv3PlusSvelteBinding } from "@netease-mini-player/v3-plus/svelte";

  const binding = createNMPv3PlusSvelteBinding({
    playlistId: "14273792576",
    sourceType: "local-json",
    source: "/music/playlist.json",
    skin: "vinyl",
    plusExtensions: ["advanced-layouts", "visualizer", "custom-source"],
    plusLayout: "cover",
    extensionUrl: "/extensions/user/wave/manifest.json",
    lyric: true,
  });

  onMount(async () => {
    await import("@netease-mini-player/v3/auto");
    await import("@netease-mini-player/v3-plus");
  });
</script>

<svelte:element this={binding.tagName} {...binding.props} />

// nmpv3-plus/examples/next/NMPv3PlusPlayer.tsx
"use client";

import "netease-mini-player-v3/auto";
import { createNMPv3PlusNextClientPlan } from "netease-mini-player-v3-plus/next";

const plan = createNMPv3PlusNextClientPlan({
  playlistId: "14273792576",
  sourceType: "local-json",
  source: "/music/playlist.json",
  skin: "glass",
  plusLayout: "cover",
  plusExtensions: ["advanced-layouts", "custom-source", "local-lyrics"],
  lyricsUrl: "/lyrics/song.lrc",
  translationLyricsUrl: "/lyrics/song.zh.lrc",
  lyric: true,
});

export function NMPv3PlusPlayer() {
  return <nmp-player {...plan.element.attrs} />;
}
